### ISSUE TITLE
Goruntu isleme / YOLO

### ISSUE THREAD

**Issue by C4MCI** [C4MCI/Navida#3]
Idada kullanacagimiz goruntu isleme algortirmasi yine yolo. BIr iki paragraf bir sey yazilmasi lazim. ida icin de yazmistik zaten benzer sekilde ama ayni cumlelerden olmayacak sekilde yazalim.

**Comment by C4MCI** [comment]
Iletisimin ros ile olacagini da ekleyebiliriz bir cumle ile

**Comment by mileself** [comment]
deneme
