### ISSUE TITLE
Genel gorev algoritmasi ve flowchart

### ISSUE THREAD

**Issue by C4MCI** [C4MCI/Navida#4]
X ticketinda bahsedilen genel olarak ihanin gorev algoritmasinin guzel bir sekilde yazilmasi ve gorevin flowchart diagraminin yapilmasi gerekiyor.

**Comment by C4MCI** [comment]
flowcharti ben yapacagim. Algoritmayi ona bakarak yazabilirsiniz.

**Comment by C4MCI** [comment]
iletisimin ros ile saglanacagini da paragrafa ekleyelim

**Comment by C4MCI** [comment]
![Image](https://github.com/C4MCI/Navida/assets/45119614/95ba8f87-9e81-4dc8-a063-cc2ca0be174f)

geldi abim flowchart

**Comment by MustafaSPN** [comment]
abim uzunluk ne kadar olmalı? bir de bahsedilen algoritmalara detayına girmeden bu algoritma kullanılarak şöyle yapılır tarzında mı yazmalıyım

**Comment by MustafaSPN** [comment]
mesela numaraya doğru ilerle kısmında nasıl ilerleyeceğini de detaylı açıklamamız lazım mı

**Comment by C4MCI** [comment]
Genel olarak gorev algoritmasi yazdigin icin detayli aciklamana gerek yok. Sadece algoritmanin isimlerini kullanalim mesela obje tespiti degil de yolo diyelim. Ihanin hareketi nasil olacak tam ben de bilmiyorum zaten bahsetmemize gerek yok mekanik takim bahseder onu

**Comment by MustafaSPN** [comment]
Başlangıçta, İHA’nın sensör verileri başlatılır ve gerekli tüm parametreler kontrol edilir. Eğer tüm parametreler beklenildiği gibi ise, İHA uçuş kontrol algoritması aracılığıyla havalandırılır. Çevre, YOLO adlı görüntü işleme modeli aracılığıyla taranır ve İDA’nın yanaşması gereken liman numarası aranır. İstenilen numara tespit edildikten sonra, İHA tarafından görüntü işleme algoritmasından (YOLO) alınan veriler doğrultusunda, İDA’nın yanaşması gereken limana bir rota oluşturulur ve bu rota takip edilir. Limanın tam üzerine, yani rotanın bitiş konumuna ulaşıldığında, mevcut konumun GPS koordinatları kablosuz verici aracılığıyla İDA’ya iletilir. İHA’nın İDA ile olan iletişimi ve algoritmalar arası veri geçişleri, robotik işletim sistemi olan ROS ile sağlanır.

**Comment by MustafaSPN** [comment]
Eklemem veya değiştirmem gereken bir şeyler var mı

**Comment by C4MCI** [comment]
Ellerine sağlık abim worde ekleyelim zaten üzerinden bir tur geçeriz pazartesi günü aklımıza bir şey gelirse ekleriz

**Comment by MustafaSPN** [comment]
Tamamdır abim
